# API related
calculate_endpoint = "/feecalc"

# Calculator related


BASE_DELIVERY_FEE = 2.0
BASE_DELIVERY_FEE_DISTANCE = 1000

ADDITIONAL_FEE = 1.0
ADDITIONAL_FEE_DISTANCE = 500


ADDITIONAL_ITEM_LIMIT = 5
ADDITIONAL_ITEM_SURCHARGE = 0.5

# Maximum fee for the delivery
MAX_FEE = 15.0

# Rush hour related
RUSH_MULTIPLIER = 1.2
RUSH_DELIVERY_DAY = 4
RUSH_DELIVERY_START = 15
RUSH_DELIVERY_END = 19


FREE_DELIVERY_THRESHOLD = 200.0
SMALL_ORDER_THRESHOLD = 10.0

BULK_FEE_THRESHOLD = 12
BULK_FEE = 1.20

